version: "3.9"
services:

  redis:
    image: redis
    container_name: rediss
    ports:
     - "6379:6379"
    command:  redis-server --save 60 1 --loglevel warning 
    restart: always

  backend:
    build: .
    container_name: todo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False

  worker-celery:
    build: .
    volumes:
      - ./core:/app
    command: bash -c "celery -A core worker -l INFO & celery -A core beat -l INFO"
    depends_on:
      - backend
      - redis