version: "3.9"
services:
  redis:
    image: redis
    container_name: rediss
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    restart: always

  backend:
    build: .
    container_name: todo
    command: gunicorn -c /app/gunicorn.conf.py core.wsgi:application
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"

  # workers-celery:
  #   build: .
  #   volumes:
  #     - ./core:/app
  #   command: bash -c "celery -A core worker -l INFO & celery -A core beat -l INFO"
  #   depends_on:
  #     - backend
  #     - redis
  
  nginx:
    image: nginx
    container_name: todo-nginx
    restart: always
    ports:
      - '8081:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend
      - redis

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  # smtp4dev:
  #   image: rnwood/smtp4dev:v3
  #   restart: always
  #   ports:
  #     - '5000:80'
  #     - '25:25'
  #     - '143:143'
  #   volumes:
  #       - smtp4dev-data:/smtp4dev
  #   environment:
  #     - ServerOptions__Urls=http://*:80
  #     - ServerOptions__HostName=smtp4dev

  # master:
  #   image: locustio/locust
  #   ports:
  #    - "8089:8089"
  #   volumes:
  #     - ./core/locust:/mnt/locust
  #   command: -f /mnt/locust/locustfile.py --master -H http://backend:8000/
  
  # worker:
  #   image: locustio/locust
  #   volumes:
  #     - ./core/locust:/mnt/locust
  #   command: -f /mnt/locust/locustfile.py --worker --master-host master


volumes:
  smtp4dev-data:
  static_volume:
  media_volume:
  postgres_data: