version: "3.9"
services:

  redis:
    image: redis
    container_name: rediss
    ports:
     - "6379:6379"
    command:  redis-server --save 60 1 --loglevel warning 
    restart: always

  backend:
    build: .
    container_name: todo
    command: gunicorn -c /app/gunicorn.conf.py core.wsgi:application
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False

  workers-celery:
    build: .
    volumes:
      - ./core:/app
    command: bash -c "celery -A core worker -l INFO & celery -A core beat -l INFO"
    depends_on:
      - backend
      - redis
  
  nginx:
    image: nginx
    container_name: todo-nginx
    restart: always
    ports:
      - '8081:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend
      - redis

volumes:
  static_volume:
  media_volume: